// All UI copy in Bangla. No em dashes.

export const L = {
  appName: 'কুরআন বুঝে পড়ি',
  continue: 'চালিয়ে যান',
  todayPassage: 'আজকের পাঠ',
  reviewsDue: 'রিভিউ বাকি',
  progress: 'সালাতের সূরার শব্দ চেনা',
  allSurahs: 'সূরাসমূহ',
  ayahs: 'আয়াত',
  words: 'শব্দ',
  about: 'উৎস ও লাইসেন্স',
  home: 'হোম',
  settings: 'সেটিংস',
  fontSize: 'আরবি লেখার আকার',
  theme: 'থিম',
  themeLight: 'আলো',
  themeDark: 'অন্ধকার',
  themeSystem: 'ডিভাইস অনুযায়ী',
  support: 'শব্দের অর্থ দেখান',
  supportAll: 'সব',
  supportNew: 'শুধু নতুন শব্দ',
  supportNone: 'কিছুই না',
  play: 'তিলাওয়াত শুনুন',
  pause: 'থামান',
  audioOffline: 'অডিওর জন্য ইন্টারনেট লাগবে',
  close: 'বন্ধ করুন',
  meaning: 'অর্থ',
  englishMeaning: 'ইংরেজি অর্থ',
  bnMissing: 'বাংলা অর্থ এখনো যোগ হয়নি',
  root: 'মূল অক্ষর (রুট)',
  noRoot: 'এই শব্দের রুট নেই',
  rootMeaningMissing: 'রুটের মূল অর্থ এখনো যোগ হয়নি',
  pattern: 'গঠন (প্যাটার্ন)',
  noPattern: 'নির্দিষ্ট প্যাটার্ন চিহ্নিত নয়',
  needsReview: 'যাচাই বাকি',
  lemma: 'মূল শব্দ',
  siblings: 'একই পরিবারের শব্দ',
  sameRoot: 'একই রুট',
  samePattern: 'একই প্যাটার্ন',
  addToReview: 'রিভিউতে যোগ করুন',
  addedToReview: 'রিভিউতে আছে',
  markKnown: 'এই শব্দটি চিনি',
  known: 'চেনা শব্দ',
  tabTranslations: 'অনুবাদ',
  tabTafsir: 'তাফসীর',
  tabNote: 'আমার নোট',
  translator: 'অনুবাদক',
  showTranslations: 'কোন অনুবাদ দেখাবেন',
  footnotes: 'টীকা',
  essence: 'সারকথা',
  summary: 'সংক্ষেপ',
  lessons: 'শিক্ষা',
  heart: 'অন্তরের অর্থ',
  fullTafsir: 'পূর্ণ তাফসীর',
  originalSource: 'মূল উৎস',
  unreviewed: 'অযাচাইকৃত সারাংশ',
  reviewed: 'যাচাইকৃত',
  markReviewed: 'মূলের সাথে মিলিয়ে দেখেছি',
  noSummaries: 'এই আয়াতের সারাংশ এখনো তৈরি হয়নি। নিচে মূল তাফসীর দেখুন।',
  source: 'উৎস',
  notePlaceholder: 'এই আয়াত নিয়ে আপনার ভাবনা লিখুন...',
  saved: 'সংরক্ষিত',
  doneForToday: 'আজকের জন্য শেষ',
  doneForTodayBody: 'আজ যথেষ্ট পড়েছেন। চাইলে আরও পড়তে পারেন, না হলে কাল আবার দেখা হবে।',
  keepGoing: 'আরও পড়ব',
  goHome: 'হোমে ফিরুন',
  streak: 'টানা দিন',
  days: 'দিন',
  minutesToday: 'আজ পড়েছেন',
  minutes: 'মিনিট',
  ayahNo: 'আয়াত',
  surah: 'সূরা',
  next: 'পরের সূরা',
  prev: 'আগের সূরা',
  offlineReady: 'অফলাইনে ব্যবহারের জন্য প্রস্তুত',
  version: 'সংস্করণ',
  downloaded: 'ডাউনলোডের তারিখ',
  license: 'লাইসেন্স',
  notes: 'নোট',
  legendRoot: 'রুট অক্ষর',
  legendPattern: 'প্যাটার্ন অক্ষর',
  legendAffix: 'উপসর্গ / প্রত্যয়',
} as const;

const BN_DIGITS = '০১২৩৪৫৬৭৮৯';
export const bn = (n: number | string) => String(n).replace(/\d/g, (d) => BN_DIGITS[Number(d)]);

const AR_DIGITS = '٠١٢٣٤٥٦٧٨٩';
export const ar = (n: number | string) => String(n).replace(/\d/g, (d) => AR_DIGITS[Number(d)]);
