// Writes out/sw.js after `next build`. Precaches every exported file so the app works offline.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const OUT = 'out';

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const files = walk(OUT).filter((f) => !f.endsWith('sw.js') && !f.endsWith('.map'));
const hash = createHash('sha256');
const urls = files.map((f) => {
  hash.update(readFileSync(f));
  let url = '/' + relative(OUT, f).split(sep).join('/');
  if (url.endsWith('/index.html')) url = url.slice(0, -'index.html'.length);
  return url;
});
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.ts. Do not edit.
const CACHE = 'quran-learn-${version}';
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;

  // Pages: try the cached page for this path (with or without trailing slash), then network.
  if (req.mode === 'navigate') {
    const path = url.pathname.endsWith('/') ? url.pathname : url.pathname + '/';
    event.respondWith(
      caches.match(path, { cacheName: CACHE })
        .then((hit) => hit || fetch(req))
        .catch(() => caches.match('/', { cacheName: CACHE })),
    );
    return;
  }

  // Everything else (JS, CSS, fonts, data, RSC payloads): cache first, ignoring ?_rsc= query.
  event.respondWith(
    caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files precached, version ${version}`);
