// Post-build for the static export:
// 1. Copies Next segment prefetch files to the flat names the client requests.
// 2. Writes out/sw.js, which precaches every exported file so the app works offline.
import { createHash } from 'node:crypto';
import { copyFileSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const OUT = 'out';

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

// Next 16 writes e.g. recite/1/__next.recite/$d$surah/__PAGE__.txt but the client fetches
// recite/1/__next.recite.$d$surah.__PAGE__.txt. Static hosts need the flat copy.
for (const f of walk(OUT)) {
  const parts = relative(OUT, f).split(sep);
  const i = parts.findIndex((p, k) => p.startsWith('__next.') && k < parts.length - 1);
  if (i === -1) continue;
  const flat = join(OUT, ...parts.slice(0, i), parts.slice(i).join('.'));
  copyFileSync(f, flat);
}

// Classical tafsir (several MB) is not precached; the fetch handler caches each file on first open.
const LAZY = ['data/tafsir/'];
const files = walk(OUT).filter((f) => {
  const rel = relative(OUT, f).split(sep);
  if (f.endsWith('sw.js') || f.endsWith('.map')) return false;
  if (rel.slice(0, -1).some((p) => p.startsWith('__next.'))) return false;
  return !LAZY.some((p) => rel.join('/').startsWith(p));
});
const hash = createHash('sha256');
const urls = files.map((f) => {
  hash.update(readFileSync(f));
  let url = '/' + relative(OUT, f).split(sep).join('/');
  if (url.endsWith('/index.html')) url = url.slice(0, -'index.html'.length);
  return url;
});
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.ts. Do not edit.
const CACHE = 'quran-learn-${version}';
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Next checks routes with HEAD requests. Answer them from the cache when offline.
  if (req.method === 'HEAD') {
    event.respondWith(
      fetch(req).catch(() =>
        caches.match(url.pathname, { cacheName: CACHE }).then((hit) =>
          hit ? new Response(null, { status: hit.status, headers: hit.headers }) : Response.error(),
        ),
      ),
    );
    return;
  }
  if (req.method !== 'GET') return;

  // Pages: try the cached page for this path (with or without trailing slash), then network.
  if (req.mode === 'navigate') {
    const path = url.pathname.endsWith('/') ? url.pathname : url.pathname + '/';
    event.respondWith(
      caches.match(path, { cacheName: CACHE })
        .then((hit) => hit || fetch(req))
        .catch(() => caches.match('/', { cacheName: CACHE })),
    );
    return;
  }

  // Everything else (JS, CSS, fonts, data, RSC payloads): cache first, ignoring ?_rsc= query.
  event.respondWith(
    caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files precached, version ${version}`);
